# Generated by Django 4.1.4 on 2023-01-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_basket_products_basketitem_basket_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ['basket']},
        ),
        migrations.RemoveField(
            model_name='basket',
            name='items',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='products',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='user',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.basket'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.product'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
